name: QuackSaftey
version: ${project.version}
main: com.hicupalot.quacksaftey.QuackSaftey
api-version: 1.16
authors: [hicupalot]
description: The Plugin to Keep Players Safe

commands:
  didibreakit:
    description: Tells you if you really messed it up
    usage: /didibreakit
    permission: quacksaftey.doesitwork
    aliases: hicuptest
  barrier:
    description: Gives you a barrier
    usage: /barrier
  colourcodes:
    description: Shows you the colour codes
    usage: /colourcodes
    permission: quacksaftey.colour
    aliases: colorcodes
  discord:
    description: gives you the Quacktopia Discord Link
    usage: /discord
    permission: quacksaftey.discord
  feedback:
    description: Gives the feedback website
    usage: /feedback
    permission: quacksaftey.feedback
    aliases: [suggestions, bugs]
  permissions:
      quacksaftey.nbtbypass:
          description: 'Allows you to middle click certain items which could be dangerous'
          default: op
      quacksaftey.speedingticket:
         descritpion: 'Lets you see the broadcast of speeding players'
         default: op
