name: QuackSafety
version: ${project.version}
main: com.quacktopia.quacksaftey.QuackSaftey
api-version: 1.16
authors: [hicupalot]
depend:
  - LuckPerms
  - Essentials
  - Vault
commands:
  didibreakit:
    description: Tells you if you really messed it up
    usage: /didibreakit
    permission: quacksafety.doesitwork
    aliases: hicuptest
  barrier:
    description: Gives you a barrier
    usage: /barrier
  colourcodes:
    description: Shows you the colour codes
    usage: /colourcodes
    permission: quacksafety.colour
    aliases: colorcodes
  discord:
    description: gives you the Quacktopia Discord Link
    usage: /discord
    permission: quacksafety.discord
  feedback:
    description: Gives the feedback website
    usage: /feedback
    permission: quacksafety.feedback
    aliases: [suggestions, bugs]
  playtime:
    description: Shows you the playtime of a player
    usage: /<command> <player>
    aliases: [totalplaytime]
    permission: quacksafety.playtime
  Watchlist:
    description: Adds a player to the watchlist
    usage: /<command> <player>
    permission: quacksafety.watchlist
  watchlistremove:
    description: Removes a player from the watchlist
    usage: /<command> <player>
    permission: quacksafety.watchlist

  permissions:
    quacksafety.speedingticket:
         descritpion: 'Lets you see the broadcast of speeding players'
         default: op
      quacksafety.armorstandbypass:
        description: 'Lets you bypass the 5 armour stands a chunk limit'
        default: op
      quacksafety.bookbypass:
        description: 'Lets you bypass the book ban'
        default: op
      quacksafety.itemframebypass:
        description: 'Lets you bypass the item frame warning'
        default: op
      quacksafety.dropitembypass:
        description: 'Lets you bypass the ItemDrop Warning'
        default: op
      quacksafety.laggometer:
        description: 'Allows you to view the lagg warnings'
        default: op
      quacksafety.paintingbypass:
        description: 'Allows you to bypass the Painting Warning'
        default: op
      quacksafety.staff:
        description: "The generic Staff permission"
        default: op
