name: QuackSafety
version: ${project.version}
main: com.quacktopia.quacksaftey.QuackSaftey
api-version: 1.16
authors: [hicupalot]
commands:
  didibreakit:
    description: Tells you if you really messed it up
    usage: /didibreakit
    permission: quacksaftey.doesitwork
    aliases: hicuptest
  barrier:
    description: Gives you a barrier
    usage: /barrier
  colourcodes:
    description: Shows you the colour codes
    usage: /colourcodes
    permission: quacksaftey.colour
    aliases: colorcodes
  discord:
    description: gives you the Quacktopia Discord Link
    usage: /discord
    permission: quacksaftey.discord
  feedback:
    description: Gives the feedback website
    usage: /feedback
    permission: quacksaftey.feedback
    aliases: [suggestions, bugs]
  permissions:
      quacksaftey.nbtbypass:
          description: 'Allows you to middle click certain items which could be dangerous'
          default: op
      quacksaftey.speedingticket:
         descritpion: 'Lets you see the broadcast of speeding players'
         default: op
      quacksaftey.armorstandbypass:
        description: 'Lets you bypass the 5 armour stands a chunk limit'
        default: op
      quacksaftey.bookbypass:
        description: 'Lets you bypass the book ban'
        default: op
      quacksaftey.itemframebypass:
        description: 'Lets you bypass the item frame warning'
        default: op
      quacksaftey.dropitembypass:
        description: 'Lets you bypass the ItemDrop Warning'
        default: op
      quacksaftey.laggometer:
        description: 'Allows you to view the lagg warnings'
        default: op
      quacksaftey.paintingbypass:
        description: 'Allows you to bypass the Painting Warning'
        default: op

